package models

import (
	"encoding/xml"
)

// Profile vmix profile struct
type Profile struct {
	XMLName xml.Name `xml:"XML"`
	Text    string   `xml:",chardata"`
	Version string   `xml:"Version"`
	Input   []struct {
		Text                                        string `xml:",chardata"`
		Type                                        string `xml:"Type,attr"`
		Position                                    string `xml:"Position,attr"`
		RangeStart                                  string `xml:"RangeStart,attr"`
		RangeStop                                   string `xml:"RangeStop,attr"`
		State                                       string `xml:"State,attr"`
		OriginalTitle                               string `xml:"OriginalTitle,attr"`
		ShortcutMappings                            string `xml:"ShortcutMappings,attr"`
		Key                                         string `xml:"Key,attr"`
		Loop                                        string `xml:"Loop,attr"`
		VolumeF                                     string `xml:"VolumeF,attr"`
		Muted                                       string `xml:"Muted,attr"`
		BalanceF                                    string `xml:"BalanceF,attr"`
		AspectRatio                                 string `xml:"AspectRatio,attr"`
		Category                                    string `xml:"Category,attr"`
		MouseClickAction                            string `xml:"MouseClickAction,attr"`
		Collapsed                                   string `xml:"Collapsed,attr"`
		Solo                                        string `xml:"Solo,attr"`
		HeadphonesVolumeF                           string `xml:"HeadphonesVolumeF,attr"`
		BusMaster                                   string `xml:"BusMaster,attr"`
		FrameDelay                                  string `xml:"FrameDelay,attr"`
		Positions                                   string `xml:"Positions,attr"`
		PositionsExtended                           string `xml:"PositionsExtended,attr"`
		VirtualPTZPosition                          string `xml:"VirtualPTZPosition,attr"`
		Triggers                                    string `xml:"Triggers,attr"`
		TallyCOMPort                                string `xml:"TallyCOMPort,attr"`
		TallyNumber                                 string `xml:"TallyNumber,attr"`
		AutoAudioMixing                             string `xml:"AutoAudioMixing,attr"`
		AutoPause                                   string `xml:"AutoPause,attr"`
		AutoRestart                                 string `xml:"AutoRestart,attr"`
		AutoPlay                                    string `xml:"AutoPlay,attr"`
		Mirror                                      string `xml:"Mirror,attr"`
		SelectedIndex                               string `xml:"SelectedIndex,attr"`
		Rate                                        string `xml:"Rate,attr"`
		XML                                         string `xml:"XML,attr"`
		ShaderSource                                string `xml:"ShaderSource,attr"`
		PTZProvider                                 string `xml:"PTZProvider,attr"`
		PTZConnection                               string `xml:"PTZConnection,attr"`
		PTZAutoConnect                              string `xml:"PTZAutoConnect,attr"`
		PTZDefaultPanTiltSpeed                      string `xml:"PTZDefaultPanTiltSpeed,attr"`
		PTZDefaultZoomSpeed                         string `xml:"PTZDefaultZoomSpeed,attr"`
		PTZDefaultPositionSpeed                     string `xml:"PTZDefaultPositionSpeed,attr"`
		PTZDefaultFocusSpeed                        string `xml:"PTZDefaultFocusSpeed,attr"`
		PTZDefaultFocusEnabled                      string `xml:"PTZDefaultFocusEnabled,attr"`
		PTZAlwaysShowThumbnail                      string `xml:"PTZAlwaysShowThumbnail,attr"`
		Colour                                      string `xml:"Colour,attr"`
		ColourBars                                  string `xml:"ColourBars,attr"`
		VideoShaderColorCorrectionSourceEnabled     string `xml:"VideoShader_ColorCorrectionSourceEnabled,attr"`
		VideoShaderWhite                            string `xml:"VideoShader_White,attr"`
		VideoShaderBlack                            string `xml:"VideoShader_Black,attr"`
		VideoShaderRed                              string `xml:"VideoShader_Red,attr"`
		VideoShaderGreen                            string `xml:"VideoShader_Green,attr"`
		VideoShaderBlue                             string `xml:"VideoShader_Blue,attr"`
		VideoShaderAlpha                            string `xml:"VideoShader_Alpha,attr"`
		VideoShaderSaturation                       string `xml:"VideoShader_Saturation,attr"`
		VideoShaderCCLiftR                          string `xml:"VideoShader_CCLiftR,attr"`
		VideoShaderCCLiftG                          string `xml:"VideoShader_CCLiftG,attr"`
		VideoShaderCCLiftB                          string `xml:"VideoShader_CCLiftB,attr"`
		VideoShaderCCGammaR                         string `xml:"VideoShader_CCGammaR,attr"`
		VideoShaderCCGammaG                         string `xml:"VideoShader_CCGammaG,attr"`
		VideoShaderCCGammaB                         string `xml:"VideoShader_CCGammaB,attr"`
		VideoShaderCCGainR                          string `xml:"VideoShader_CCGainR,attr"`
		VideoShaderCCGainG                          string `xml:"VideoShader_CCGainG,attr"`
		VideoShaderCCGainB                          string `xml:"VideoShader_CCGainB,attr"`
		VideoShaderSaturation2                      string `xml:"VideoShader_Saturation2,attr"`
		VideoShaderHue                              string `xml:"VideoShader_Hue,attr"`
		VideoShaderRec601Fix                        string `xml:"VideoShader_Rec601Fix,attr"`
		VideoShaderColorKey                         string `xml:"VideoShader_ColorKey,attr"`
		VideoShaderDeinterlace                      string `xml:"VideoShader_Deinterlace,attr"`
		VideoShaderSharpen                          string `xml:"VideoShader_Sharpen,attr"`
		VideoShaderToleranceRed                     string `xml:"VideoShader_ToleranceRed,attr"`
		VideoShaderToleranceGreen                   string `xml:"VideoShader_ToleranceGreen,attr"`
		VideoShaderToleranceBlue                    string `xml:"VideoShader_ToleranceBlue,attr"`
		VideoShaderToleranceGreenGap                string `xml:"VideoShader_ToleranceGreenGap,attr"`
		VideoShaderGreenFilter                      string `xml:"VideoShader_GreenFilter,attr"`
		VideoShaderGreenFilterTransparencyThreshold string `xml:"VideoShader_GreenFilterTransparencyThreshold,attr"`
		VideoShaderLumaKeyThreshold                 string `xml:"VideoShader_LumaKeyThreshold,attr"`
		VideoShaderAntiAliasing                     string `xml:"VideoShader_AntiAliasing,attr"`
		VideoShaderAntiAliasingFilter               string `xml:"VideoShader_AntiAliasingFilter,attr"`
		VideoShaderClippingX1                       string `xml:"VideoShader_ClippingX1,attr"`
		VideoShaderClippingX2                       string `xml:"VideoShader_ClippingX2,attr"`
		VideoShaderClippingY1                       string `xml:"VideoShader_ClippingY1,attr"`
		VideoShaderClippingY2                       string `xml:"VideoShader_ClippingY2,attr"`
		VideoShaderPremultipliedAlpha               string `xml:"VideoShader_PremultipliedAlpha,attr"`
		MixerCollapsed                              string `xml:"MixerCollapsed,attr"`
		MixerVisible                                string `xml:"MixerVisible,attr"`
		VideoInterlaced                             string `xml:"VideoInterlaced,attr"`
		AudioDelay                                  string `xml:"AudioDelay,attr"`
		AudioChannel                                string `xml:"AudioChannel,attr"`
		AudioGain                                   string `xml:"AudioGain,attr"`
		AudioPad                                    string `xml:"AudioPad,attr"`
		AudioCompressorEnabled                      string `xml:"AudioCompressorEnabled,attr"`
		AudioCompressorRatio                        string `xml:"AudioCompressorRatio,attr"`
		AudioCompressorThreshold                    string `xml:"AudioCompressorThreshold,attr"`
		AudioNoiseGateEnabled                       string `xml:"AudioNoiseGateEnabled,attr"`
		AudioNoiseGateThreshold                     string `xml:"AudioNoiseGateThreshold,attr"`
		AudioEQEnabled                              string `xml:"AudioEQEnabled,attr"`
		AudioEQGainDB0                              string `xml:"AudioEQGainDB0,attr"`
		AudioEQGainDB1                              string `xml:"AudioEQGainDB1,attr"`
		AudioEQGainDB2                              string `xml:"AudioEQGainDB2,attr"`
		AudioEQGainDB3                              string `xml:"AudioEQGainDB3,attr"`
		AudioEQGainDB4                              string `xml:"AudioEQGainDB4,attr"`
		AudioEQGainDB5                              string `xml:"AudioEQGainDB5,attr"`
		AudioEQGainDB6                              string `xml:"AudioEQGainDB6,attr"`
		AudioEQGainDB7                              string `xml:"AudioEQGainDB7,attr"`
		AudioEQGainDB8                              string `xml:"AudioEQGainDB8,attr"`
		AudioEQGainDB9                              string `xml:"AudioEQGainDB9,attr"`
		AudioAGCEnabled                             string `xml:"AudioAGCEnabled,attr"`
		AudioRackXML                                string `xml:"AudioRackXML,attr"`
		BrowserWidth                                string `xml:"BrowserWidth,attr"`
		BrowserHeight                               string `xml:"BrowserHeight,attr"`
		BrowserMouseEnabled                         string `xml:"BrowserMouseEnabled,attr"`
		BrowserVersion                              string `xml:"BrowserVersion,attr"`
		BrowserGPUDisabled                          string `xml:"BrowserGPUDisabled,attr"`
		Title                                       string `xml:"Title,attr"`
		PresetsXML                                  string `xml:"PresetsXML,attr"`
		CountdownXML                                string `xml:"CountdownXML,attr"`
		DataSourcesXML                              string `xml:"DataSourcesXML,attr"`
		Width                                       string `xml:"Width,attr"`
		Height                                      string `xml:"Height,attr"`
		Overlay0                                    string `xml:"Overlay0,attr"`
		Overlay1                                    string `xml:"Overlay1,attr"`
		Overlay2                                    string `xml:"Overlay2,attr"`
		Overlay3                                    string `xml:"Overlay3,attr"`
		Overlay4                                    string `xml:"Overlay4,attr"`
		Overlay9                                    string `xml:"Overlay9,attr"`
		CapturePath                                 string `xml:"CapturePath,attr"`
		CaptureVMR                                  string `xml:"CaptureVMR,attr"`
		Input                                       string `xml:"Input,attr"`
		CaptureAudioInput                           string `xml:"CaptureAudioInput,attr"`
		FrameRate                                   string `xml:"FrameRate,attr"`
		FrameRateInterlaced                         string `xml:"FrameRateInterlaced,attr"`
		CaptureAudioEnabled                         string `xml:"CaptureAudioEnabled,attr"`
		CaptureInterlaced                           string `xml:"CaptureInterlaced,attr"`
		VideoFormat                                 string `xml:"VideoFormat,attr"`
		Overlay5                                    string `xml:"Overlay5,attr"`
		AudioPath                                   string `xml:"AudioPath,attr"`
		AudioStartChannel                           string `xml:"AudioStartChannel,attr"`
		AudioChannelCount                           string `xml:"AudioChannelCount,attr"`
		Overlay6                                    string `xml:"Overlay6,attr"`
		Overlay7                                    string `xml:"Overlay7,attr"`
		Overlay8                                    string `xml:"Overlay8,attr"`
		MasterOverlayLast3                          string `xml:"MasterOverlayLast3,attr"`
		ZoomDuration                                string `xml:"ZoomDuration,attr"`
		LayerVisible0                               string `xml:"LayerVisible0,attr"`
		LayerVisible1                               string `xml:"LayerVisible1,attr"`
		LayerVisible2                               string `xml:"LayerVisible2,attr"`
		LayerVisible3                               string `xml:"LayerVisible3,attr"`
		LayerVisible4                               string `xml:"LayerVisible4,attr"`
		LayerVisible5                               string `xml:"LayerVisible5,attr"`
		MasterOverlayLast2                          string `xml:"MasterOverlayLast2,attr"`
		MasterOverlayLast1                          string `xml:"MasterOverlayLast1,attr"`
		MasterOverlayLast0                          string `xml:"MasterOverlayLast0,attr"`
	} `xml:"Input"`
	State struct {
		Text      string `xml:",chardata"`
		Main      string `xml:"Main,attr"`
		Preview   string `xml:"Preview,attr"`
		PlayLists string `xml:"PlayLists,attr"`
	} `xml:"State"`
	RecordingSettings struct {
		Text                string `xml:",chardata"`
		Size                string `xml:"Size"`
		FrameRate           string `xml:"FrameRate"`
		FrameRateInterlaced string `xml:"FrameRateInterlaced"`
	} `xml:"RecordingSettings"`
	RecordingSettings2 struct {
		Text                string `xml:",chardata"`
		Size                string `xml:"Size"`
		FrameRate           string `xml:"FrameRate"`
		FrameRateInterlaced string `xml:"FrameRateInterlaced"`
	} `xml:"RecordingSettings2"`
	MultiCorderSettings string `xml:"MultiCorderSettings"`
	OverlaySettings     struct {
		Text               string `xml:",chardata"`
		Mode0              string `xml:"Mode0"`
		Effect0            string `xml:"Effect0"`
		Duration0          string `xml:"Duration0"`
		MatrixPosition0    string `xml:"MatrixPosition0"`
		CutPoint0          string `xml:"CutPoint0"`
		BorderColor0       string `xml:"BorderColor0"`
		BorderThickness0   string `xml:"BorderThickness0"`
		BorderRadius0      string `xml:"BorderRadius0"`
		DisplayDuration0   string `xml:"DisplayDuration0"`
		Alpha0             string `xml:"Alpha0"`
		Input0             string `xml:"Input0"`
		DisplayUnderneath0 string `xml:"DisplayUnderneath0"`
		Mode1              string `xml:"Mode1"`
		Effect1            string `xml:"Effect1"`
		Duration1          string `xml:"Duration1"`
		MatrixPosition1    string `xml:"MatrixPosition1"`
		CutPoint1          string `xml:"CutPoint1"`
		BorderColor1       string `xml:"BorderColor1"`
		BorderThickness1   string `xml:"BorderThickness1"`
		BorderRadius1      string `xml:"BorderRadius1"`
		DisplayDuration1   string `xml:"DisplayDuration1"`
		Alpha1             string `xml:"Alpha1"`
		Input1             string `xml:"Input1"`
		DisplayUnderneath1 string `xml:"DisplayUnderneath1"`
		Mode2              string `xml:"Mode2"`
		Effect2            string `xml:"Effect2"`
		Duration2          string `xml:"Duration2"`
		MatrixPosition2    string `xml:"MatrixPosition2"`
		CutPoint2          string `xml:"CutPoint2"`
		BorderColor2       string `xml:"BorderColor2"`
		BorderThickness2   string `xml:"BorderThickness2"`
		BorderRadius2      string `xml:"BorderRadius2"`
		DisplayDuration2   string `xml:"DisplayDuration2"`
		Alpha2             string `xml:"Alpha2"`
		Input2             string `xml:"Input2"`
		DisplayUnderneath2 string `xml:"DisplayUnderneath2"`
		Mode3              string `xml:"Mode3"`
		Effect3            string `xml:"Effect3"`
		Duration3          string `xml:"Duration3"`
		MatrixPosition3    string `xml:"MatrixPosition3"`
		CutPoint3          string `xml:"CutPoint3"`
		BorderColor3       string `xml:"BorderColor3"`
		BorderThickness3   string `xml:"BorderThickness3"`
		BorderRadius3      string `xml:"BorderRadius3"`
		DisplayDuration3   string `xml:"DisplayDuration3"`
		Alpha3             string `xml:"Alpha3"`
		Input3             string `xml:"Input3"`
		DisplayUnderneath3 string `xml:"DisplayUnderneath3"`
		Mode4              string `xml:"Mode4"`
		Effect4            string `xml:"Effect4"`
		Duration4          string `xml:"Duration4"`
		MatrixPosition4    string `xml:"MatrixPosition4"`
		CutPoint4          string `xml:"CutPoint4"`
		BorderColor4       string `xml:"BorderColor4"`
		BorderThickness4   string `xml:"BorderThickness4"`
		BorderRadius4      string `xml:"BorderRadius4"`
		DisplayDuration4   string `xml:"DisplayDuration4"`
		Alpha4             string `xml:"Alpha4"`
		Input4             string `xml:"Input4"`
		DisplayUnderneath4 string `xml:"DisplayUnderneath4"`
		Mode5              string `xml:"Mode5"`
		Effect5            string `xml:"Effect5"`
		Duration5          string `xml:"Duration5"`
		MatrixPosition5    string `xml:"MatrixPosition5"`
		CutPoint5          string `xml:"CutPoint5"`
		BorderColor5       string `xml:"BorderColor5"`
		BorderThickness5   string `xml:"BorderThickness5"`
		BorderRadius5      string `xml:"BorderRadius5"`
		DisplayDuration5   string `xml:"DisplayDuration5"`
		Alpha5             string `xml:"Alpha5"`
		Input5             string `xml:"Input5"`
		DisplayUnderneath5 string `xml:"DisplayUnderneath5"`
	} `xml:"OverlaySettings"`
	Shortcuts struct {
		Text            string `xml:",chardata"`
		ArrayOfShortcut struct {
			Text string `xml:",chardata"`
			Xsi  string `xml:"xsi,attr"`
			Xsd  string `xml:"xsd,attr"`
		} `xml:"ArrayOfShortcut"`
	} `xml:"Shortcuts"`
	AudioMaster struct {
		Text                     string `xml:",chardata"`
		AudioDelay               string `xml:"AudioDelay,attr"`
		AudioChannel             string `xml:"AudioChannel,attr"`
		AudioGain                string `xml:"AudioGain,attr"`
		AudioPad                 string `xml:"AudioPad,attr"`
		AudioCompressorEnabled   string `xml:"AudioCompressorEnabled,attr"`
		AudioCompressorRatio     string `xml:"AudioCompressorRatio,attr"`
		AudioCompressorThreshold string `xml:"AudioCompressorThreshold,attr"`
		AudioNoiseGateEnabled    string `xml:"AudioNoiseGateEnabled,attr"`
		AudioNoiseGateThreshold  string `xml:"AudioNoiseGateThreshold,attr"`
		AudioEQEnabled           string `xml:"AudioEQEnabled,attr"`
		AudioEQGainDB0           string `xml:"AudioEQGainDB0,attr"`
		AudioEQGainDB1           string `xml:"AudioEQGainDB1,attr"`
		AudioEQGainDB2           string `xml:"AudioEQGainDB2,attr"`
		AudioEQGainDB3           string `xml:"AudioEQGainDB3,attr"`
		AudioEQGainDB4           string `xml:"AudioEQGainDB4,attr"`
		AudioEQGainDB5           string `xml:"AudioEQGainDB5,attr"`
		AudioEQGainDB6           string `xml:"AudioEQGainDB6,attr"`
		AudioEQGainDB7           string `xml:"AudioEQGainDB7,attr"`
		AudioEQGainDB8           string `xml:"AudioEQGainDB8,attr"`
		AudioEQGainDB9           string `xml:"AudioEQGainDB9,attr"`
		AudioAGCEnabled          string `xml:"AudioAGCEnabled,attr"`
		AudioRackXML             string `xml:"AudioRackXML,attr"`
		Volume                   string `xml:"Volume,attr"`
		HeadphonesVolume         string `xml:"HeadphonesVolume,attr"`
		Muted                    string `xml:"Muted,attr"`
		Collapsed                string `xml:"Collapsed,attr"`
		SendToMaster             string `xml:"SendToMaster,attr"`
	} `xml:"AudioMaster"`
	CategorySettings struct {
		Text       string `xml:",chardata"`
		AllText    string `xml:"All.Text"`
		RedText    string `xml:"Red.Text"`
		GreenText  string `xml:"Green.Text"`
		OrangeText string `xml:"Orange.Text"`
		PurpleText string `xml:"Purple.Text"`
		AquaText   string `xml:"Aqua.Text"`
		BlueText   string `xml:"Blue.Text"`
	} `xml:"CategorySettings"`
	DataSources struct {
		Text        string `xml:",chardata"`
		Datasources struct {
			Text       string `xml:",chardata"`
			Datasource []struct {
				Text         string `xml:",chardata"`
				FriendlyName string `xml:"friendlyName,attr"`
				Instance     struct {
					Text          string `xml:",chardata"`
					ID            string `xml:"id,attr"`
					Title         string `xml:"title,attr"`
					RowsAsColumns string `xml:"rowsAsColumns,attr"`
					Tables        struct {
						Text  string `xml:",chardata"`
						Table []struct {
							Text     string `xml:",chardata"`
							Name     string `xml:"name,attr"`
							Index    string `xml:"index,attr"`
							AutoNext struct {
								Text     string `xml:",chardata"`
								Enabled  string `xml:"enabled,attr"`
								Interval string `xml:"interval,attr"`
								Loop     string `xml:"loop,attr"`
							} `xml:"autoNext"`
						} `xml:"table"`
					} `xml:"tables"`
					State struct {
						Text string `xml:",chardata"`
						XML  struct {
							Text                string `xml:",chardata"`
							URL                 string `xml:"url"`
							GoogleAPIKey        string `xml:"Google_API_Key"`
							FirstRowColumnNames string `xml:"FirstRowColumnNames"`
						} `xml:"xml"`
					} `xml:"state"`
					Timer string `xml:"timer"`
				} `xml:"instance"`
			} `xml:"datasource"`
		} `xml:"datasources"`
	} `xml:"DataSources"`
	Activators struct {
		Text       string `xml:",chardata"`
		Activators string `xml:"activators"`
	} `xml:"Activators"`
	ProductionClockSettings struct {
		Text                    string `xml:",chardata"`
		ProductionClockSettings struct {
			Text           string `xml:",chardata"`
			Type           string `xml:"Type"`
			Format         string `xml:"Format"`
			StartTime      string `xml:"StartTime"`
			EndTime        string `xml:"EndTime"`
			TimeZoneOffset string `xml:"TimeZoneOffset"`
		} `xml:"ProductionClockSettings"`
	} `xml:"ProductionClockSettings"`
	ProductionClockSettings2 struct {
		Text                    string `xml:",chardata"`
		ProductionClockSettings struct {
			Text           string `xml:",chardata"`
			Type           string `xml:"Type"`
			Format         string `xml:"Format"`
			StartTime      string `xml:"StartTime"`
			EndTime        string `xml:"EndTime"`
			TimeZoneOffset string `xml:"TimeZoneOffset"`
		} `xml:"ProductionClockSettings"`
	} `xml:"ProductionClockSettings2"`
	ProductionClocksInverted string `xml:"ProductionClocksInverted"`
	MultiViewSettings        struct {
		Text           string `xml:",chardata"`
		TitleLocation  string `xml:"TitleLocation"`
		TitleHeadings  string `xml:"TitleHeadings"`
		InputMapping0  string `xml:"InputMapping0"`
		InputMapping1  string `xml:"InputMapping1"`
		InputMapping2  string `xml:"InputMapping2"`
		InputMapping3  string `xml:"InputMapping3"`
		InputMapping4  string `xml:"InputMapping4"`
		InputMapping5  string `xml:"InputMapping5"`
		InputMapping6  string `xml:"InputMapping6"`
		InputMapping7  string `xml:"InputMapping7"`
		InputMapping8  string `xml:"InputMapping8"`
		InputMapping9  string `xml:"InputMapping9"`
		InputMapping10 string `xml:"InputMapping10"`
		InputMapping11 string `xml:"InputMapping11"`
		InputMapping12 string `xml:"InputMapping12"`
		InputMapping13 string `xml:"InputMapping13"`
	} `xml:"MultiViewSettings"`
	MultiViewLayout   string `xml:"MultiViewLayout"`
	SafeAreas         string `xml:"SafeAreas"`
	WaveformPreview   string `xml:"WaveformPreview"`
	WaveformInput     string `xml:"WaveformInput"`
	StreamingSettings struct {
		Text             string `xml:",chardata"`
		SelectedIndex    string `xml:"SelectedIndex,attr"`
		StreamingSetting string `xml:"StreamingSetting"`
	} `xml:"StreamingSettings"`
	OutputFormat struct {
		Text                      string `xml:",chardata"`
		OutputSize                string `xml:"OutputSize,attr"`
		OutputFrameRate           string `xml:"OutputFrameRate,attr"`
		OutputFrameRateInterlaced string `xml:"OutputFrameRateInterlaced,attr"`
		FullscreenEnabled         string `xml:"FullscreenEnabled,attr"`
		NDIOutputExternal         string `xml:"NDIOutputExternal,attr"`
		NDIOutputExternal2        string `xml:"NDIOutputExternal2,attr"`
		NDIOutputExternal3        string `xml:"NDIOutputExternal3,attr"`
		NDIOutputExternal4        string `xml:"NDIOutputExternal4,attr"`
		OutputsExternal           struct {
			Text                        string `xml:",chardata"`
			VirtualFrameRate            string `xml:"VirtualFrameRate"`
			VirtualFrameRateInterlaced  string `xml:"VirtualFrameRateInterlaced"`
			ExternalFrameRate           string `xml:"ExternalFrameRate"`
			ExternalFrameRateInterlaced string `xml:"ExternalFrameRateInterlaced"`
			Overlay0                    string `xml:"Overlay0"`
			Overlay1                    string `xml:"Overlay1"`
			Overlay2                    string `xml:"Overlay2"`
			Overlay3                    string `xml:"Overlay3"`
			Overlay4                    string `xml:"Overlay4"`
			Overlay5                    string `xml:"Overlay5"`
			Input                       string `xml:"Input"`
			Display                     string `xml:"Display"`
			ExternalSize                string `xml:"ExternalSize"`
			VirtualSize                 string `xml:"VirtualSize"`
			ExternalDevice              string `xml:"ExternalDevice"`
			ExternalAudioDevice         string `xml:"ExternalAudioDevice"`
			ExternalAudioDelay          string `xml:"ExternalAudioDelay"`
			Virtual                     string `xml:"Virtual"`
			External                    string `xml:"External"`
			ExternalPort                string `xml:"ExternalPort"`
			ExternalAudioChannel        string `xml:"ExternalAudioChannel"`
			ExternalAlphaChannel        string `xml:"ExternalAlphaChannel"`
			VirtualUseStreaming         string `xml:"VirtualUseStreaming"`
			ExternalUseDisplay          string `xml:"ExternalUseDisplay"`
		} `xml:"OutputsExternal"`
		OutputsExternal2 struct {
			Text                        string `xml:",chardata"`
			VirtualFrameRate            string `xml:"VirtualFrameRate"`
			VirtualFrameRateInterlaced  string `xml:"VirtualFrameRateInterlaced"`
			ExternalFrameRate           string `xml:"ExternalFrameRate"`
			ExternalFrameRateInterlaced string `xml:"ExternalFrameRateInterlaced"`
			Overlay0                    string `xml:"Overlay0"`
			Overlay1                    string `xml:"Overlay1"`
			Overlay2                    string `xml:"Overlay2"`
			Overlay3                    string `xml:"Overlay3"`
			Overlay4                    string `xml:"Overlay4"`
			Overlay5                    string `xml:"Overlay5"`
			Input                       string `xml:"Input"`
			Display                     string `xml:"Display"`
		} `xml:"OutputsExternal2"`
		OutputsExternal3 struct {
			Text     string `xml:",chardata"`
			Overlay0 string `xml:"Overlay0"`
			Overlay1 string `xml:"Overlay1"`
			Overlay2 string `xml:"Overlay2"`
			Overlay3 string `xml:"Overlay3"`
			Overlay4 string `xml:"Overlay4"`
			Overlay5 string `xml:"Overlay5"`
			Input    string `xml:"Input"`
			Display  string `xml:"Display"`
		} `xml:"OutputsExternal3"`
		OutputsExternal4 struct {
			Text     string `xml:",chardata"`
			Overlay0 string `xml:"Overlay0"`
			Overlay1 string `xml:"Overlay1"`
			Overlay2 string `xml:"Overlay2"`
			Overlay3 string `xml:"Overlay3"`
			Overlay4 string `xml:"Overlay4"`
			Overlay5 string `xml:"Overlay5"`
			Input    string `xml:"Input"`
			Display  string `xml:"Display"`
		} `xml:"OutputsExternal4"`
		OutputsFullscreen struct {
			Text     string `xml:",chardata"`
			Overlay0 string `xml:"Overlay0"`
			Overlay1 string `xml:"Overlay1"`
			Overlay2 string `xml:"Overlay2"`
			Overlay3 string `xml:"Overlay3"`
			Overlay4 string `xml:"Overlay4"`
			Overlay5 string `xml:"Overlay5"`
			Input    string `xml:"Input"`
			Display  string `xml:"Display"`
		} `xml:"OutputsFullscreen"`
		OutputsFullscreen2 struct {
			Text     string `xml:",chardata"`
			Overlay0 string `xml:"Overlay0"`
			Overlay1 string `xml:"Overlay1"`
			Overlay2 string `xml:"Overlay2"`
			Overlay3 string `xml:"Overlay3"`
			Overlay4 string `xml:"Overlay4"`
			Overlay5 string `xml:"Overlay5"`
			Input    string `xml:"Input"`
			Display  string `xml:"Display"`
		} `xml:"OutputsFullscreen2"`
	} `xml:"OutputFormat"`
}
